language: "haskell"
sudo: false
install:
#  - "travis_retry cabal install 'cpphs >= 1.18.3' 'happy >= 1.19.5'"
#  - "cabal install --dry-run -v3"
#  - "travis_retry cabal install --force-reinstalls --only-dependencies -ftest"
language: nix
script:
  - nix-build release.nix -A fay_ALL
#  - fay-tests --num-threads=4 -random 20
# notifications:
#   irc:
#     channels: "irc.freenode.net#fay"
#     skip_join: true
#   email:
#     recipients: adam@bergmark.nl
#     on_success: change
#     on_failure: change
